<a href="https://colab.research.google.com/github/tmdgusya/install-pytorch-re/blob/main/torch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
from torch import nn
x = torch.tensor([1.])
model = nn.Linear(1,1)
print(model)

print(model.weight)
print(model.bias)

y = model(x)
print(y)

y2 = x @ model.weight + model.bias
print(y2)

Linear(in_features=1, out_features=1, bias=True)
Parameter containing:
tensor([[-0.1756]], requires_grad=True)
Parameter containing:
tensor([-0.7085], requires_grad=True)
tensor([-0.8841], grad_fn=<ViewBackward0>)
tensor([-0.8841], grad_fn=<AddBackward0>)


In [5]:
fc1 = nn.Linear(1,3)
fc2 = nn.Linear(3,1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

x = torch.tensor([1.])
y2 = (x @ fc1.weight.T + fc1.bias) @ fc2.weight.T + fc2.bias
print(y2)

x

Parameter containing:
tensor([[0.7934],
        [0.0055],
        [0.7788]], requires_grad=True)
Parameter containing:
tensor([-0.8658, -0.1453,  0.6176], requires_grad=True)
Parameter containing:
tensor([[ 0.4597,  0.4598, -0.0211]], requires_grad=True)
Parameter containing:
tensor([-0.5773], requires_grad=True)
tensor([-0.7044], grad_fn=<AddBackward0>)


tensor([1.])

In [11]:
x = torch.randn(5,2) # 다섯명의 키, 몸무게 데이터(한 행(채널)이 키, 몸무게) => 차원은 특정 정보를 표현. (그것이 묶음 일수도 있음)
model = nn.Linear(2, 3)

z = model(x)
z.shape # 5,3

x1 = torch.randn(4,5,2) # 4개 벌크로 넣기도 가능 위와 같이
ux = torch.unsqueeze(x, dim=0)
print(ux.shape) # 1,5,2 (더하기 위해 싱글 차원 추가 맨앞에)
a = ux + x1
a.shape

torch.Size([1, 5, 2])


torch.Size([4, 5, 2])